development:
  api_key: your_api_key
  secret_key: your_secret_key
  v: 1.0
  format: xml
  host: sandbox

test:
  api_key: 
  secret_key: 
  v: 1.0
  format: xml   
  host: sandbox 

production:
  api_key: 
  secret_key: 
  v: 1.0
  format: xml   
  host: sandbox 
